name = "How to read PDF"
version = "0.0.2"
usage = "Use this when user asks to read PDF"
usage_examples = ["Read this PDF", "Can you give me Markdown of this PDF?"]
default_status = "enabled"
content_type = "api"
content = "file://./read_pdf_as_markdown.py"
